spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: mysql
    show-sql: true
    hibernate.ddl-auto: update
    open-in-view: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
  mail:
    properties.mail.smtp:
      connecttimeout: 5000
      timeout: 3000
      writetimeout: 5000
      starttls.enable: true
      auth: true
    host: smtp.gmail.com
    password: ${OUTLOOK_MAIL_PASSWORD}
    port: 587
    username: ${OUTLOOK_MAIL_USERNAME}
  sql:
    init:
      platform: mysql
      mode: always

# API CONFIGURATION
exchange.rates.api.endpoint: https://api.apilayer.com/exchangerates_data/convert
bad.words.api.endpoint: https://api.apilayer.com/bad_words
kanye.west.api.endpoint: https://api.kanye.rest
whoisxml:
  api:
    endpoint: https://emailverification.whoisxmlapi.com/api/v3
    key: ${MAIL_API_KEY}
api.layer.key: ${API_LAYER_KEY}

# Shop owner email address:
admin.mail: ${ADMIN_MAIL}